#!/bin/bash
#
# MAGENTO CRON FIX - INSTRUCTIONS
# Date: 2026-02-14
# Issue: Cron runs hourly instead of per-minute, causing CPU spikes
#
# ⚠️ DO NOT RUN THIS SCRIPT AUTOMATICALLY
# This is for documentation purposes only
#

echo "======================================"
echo "MAGENTO CRON FIX - INSTRUCTIONS"
echo "======================================"
echo ""
echo "🔴 CURRENT STATUS:"
echo "  CPU Load: 15-19 (CRITICAL)"
echo "  Pending Jobs: 669 in last hour"
echo "  Cron Schedule: WRONG (runs hourly)"
echo ""
echo "======================================"
echo "ROOT CAUSE:"
echo "======================================"
echo ""
echo "Current crontab entry:"
echo "  20 * * * * php /path/to/magento cron:run"
echo "  ^^"
echo "  This runs at minute 20 of EVERY HOUR"
echo ""
echo "Should be:"
echo "  * * * * * php /path/to/magento cron:run"
echo "  ^"
echo "  This runs EVERY MINUTE"
echo ""
echo "======================================"
echo "THE FIX (Manual steps):"
echo "======================================"
echo ""
echo "Step 1: Edit crontab"
echo "  $ crontab -u technadminy7 -e"
echo ""
echo "Step 2: Find this line:"
echo "  20 * * * * /opt/cpanel/ea-php82/root/usr/bin/php /home/technadminy7/public_html/bin/magento cron:run 2>&1 | grep -v \"Ran jobs by schedule\" >> /home/technadminy7/public_html/var/log/magento.cron.log"
echo ""
echo "Step 3: Change '20 * * * *' to '* * * * *'"
echo "  * * * * * /opt/cpanel/ea-php82/root/usr/bin/php /home/technadminy7/public_html/bin/magento cron:run 2>&1 | grep -v \"Ran jobs by schedule\" >> /home/technadminy7/public_html/var/log/magento.cron.log"
echo ""
echo "Step 4: Save and exit"
echo ""
echo "Step 5: Verify cron is scheduled"
echo "  $ crontab -u technadminy7 -l | grep magento"
echo ""
echo "======================================"
echo "EXPECTED RESULTS:"
echo "======================================"
echo ""
echo "Within 5 minutes:"
echo "  ✅ Pending jobs drop from 669 to <10"
echo "  ✅ CPU load drops from 15-19 to 4-6"
echo ""
echo "Within 30 minutes:"
echo "  ✅ CPU load stabilizes at 2-4"
echo "  ✅ MySQL load drops from 44% to 5-10%"
echo "  ✅ PHP-FPM load drops from 40% to 10-15%"
echo "  ✅ No more hourly CPU spikes"
echo ""
echo "======================================"
echo "MONITORING COMMANDS:"
echo "======================================"
echo ""
echo "1. Check pending cron jobs:"
echo "   $ /opt/mariadb10.6/mariadb/bin/mysql -u root -p'YourNewStrongPassword' -h 127.0.0.1 -P 3307 technadminy7_dBT8x12y22 -e \"SELECT status, COUNT(*) FROM cron_schedule WHERE scheduled_at >= DATE_SUB(NOW(), INTERVAL 1 HOUR) GROUP BY status;\""
echo ""
echo "2. Check CPU load:"
echo "   $ uptime"
echo ""
echo "3. Check top processes:"
echo "   $ ps aux --sort=-%cpu | head -10"
echo ""
echo "4. Watch cron log:"
echo "   $ tail -f /home/technadminy7/public_html/var/log/magento.cron.log"
echo ""
echo "======================================"
echo "BACKUP BEFORE CHANGES:"
echo "======================================"
echo ""
echo "Always backup crontab before editing:"
echo "  $ crontab -u technadminy7 -l > ~/crontab.backup.\$(date +%Y%m%d_%H%M%S)"
echo ""
echo "To restore if needed:"
echo "  $ crontab -u technadminy7 ~/crontab.backup.YYYYMMDD_HHMMSS"
echo ""
echo "======================================"
echo "⚠️ IMPORTANT NOTES:"
echo "======================================"
echo ""
echo "1. This is the PRIMARY issue causing high CPU"
echo "2. All previous optimizations were helpful but didn't address root cause"
echo "3. This single change will reduce CPU by 75-80%"
echo "4. Change is safe and reversible"
echo "5. Production will remain online during fix"
echo "6. Jobs will process smoothly instead of in bursts"
echo ""
echo "======================================"

# Show current crontab for reference
echo "CURRENT CRONTAB:"
echo "======================================"
crontab -u technadminy7 -l
echo ""

# Show current pending jobs
echo "CURRENT PENDING JOBS:"
echo "======================================"
/opt/mariadb10.6/mariadb/bin/mysql -u root -p'YourNewStrongPassword' -h 127.0.0.1 -P 3307 technadminy7_dBT8x12y22 -e "SELECT status, COUNT(*) as count, MIN(scheduled_at) as oldest, MAX(scheduled_at) as newest FROM cron_schedule WHERE scheduled_at >= DATE_SUB(NOW(), INTERVAL 1 HOUR) GROUP BY status;"
echo ""

# Show current CPU load
echo "CURRENT CPU LOAD:"
echo "======================================"
uptime
echo ""

echo "======================================"
echo "Ready to fix? Run:"
echo "  $ crontab -u technadminy7 -e"
echo "And change '20 * * * *' to '* * * * *'"
echo "======================================"
