# Consolidated Akeneo PIM Configuration
DocumentRoot /home/pim/public_html/public

<Directory /home/pim/public_html/public>
    Options -Indexes +FollowSymLinks
    AllowOverride All
    Require all granted
    DirectoryIndex index.php
</Directory>
