<?php
$_config                 = $this->helper('Sm\Themecore\Helper\Data');
$store_id                = $_config->getStoreId();
$_css_load_file          = $this->helper('Sm\Themecore\Helper\Cssconfig');
$bodyFont                = $_config->getGeneral('bodyfont_group/body_font');
$enableElementGoogleFont = $_config->getGeneral('element_googlefont_group/use_element_googlefont');
$enableStoreCode         = $_config->getCoreConfig('web/url/use_store');
$baseURL                 = $_config->getCoreConfig('web/unsecure/base_url');
?>
<?php if ($bodyFont == 'google_font') {
    echo $_config->getGeneral('bodyfont_group/body_googlefont_link');
} ?>

<?php if ($enableElementGoogleFont) {
    echo $_config->getGeneral('element_googlefont_group/element_googlefont_link');
} ?>

<link rel="stylesheet" type="text/css" media="all" href="<?php echo $_css_load_file->getSettingsFile() ?>"/>

<script>
  window.OneSignalDeferred = window.OneSignalDeferred || [];
  OneSignalDeferred.push(async function(OneSignal) {
    await OneSignal.init({
      appId: "ea60f1be-864c-4710-9437-3288e8e06cc4",
      serviceWorkerPath: "/OneSignalSDKWorker.js",
      serviceWorkerScope: "/",
      notifyButton: {
        enable: true
      },
      promptOptions: {
        slidedown: {
          enabled: true,
          actionMessage: "هل ترغب في الحصول على أحدث العروض والتنبيهات من موقعنا؟",
          acceptButtonText: "نعم، بالتأكيد",
          cancelButtonText: "لاحقًا"
        }
      }
    });

    // Tracking events after initialization
    OneSignal.on('subscriptionChange', function (isSubscribed) {
      dataLayer.push({
        event: 'onesignal_subscription',
        status: isSubscribed
      });
    });

    OneSignal.on('notificationDisplay', function (event) {
      dataLayer.push({
        event: 'onesignal_notification_displayed',
        messageId: event.id
      });
    });

    OneSignal.on('notificationClick', function (event) {
      dataLayer.push({
        event: 'onesignal_notification_clicked',
        messageId: event.id
      });
    });
  });
</script>

<?php if ($enableStoreCode) { ?>
    <script type="text/javascript">
        require([
            'jquery',
            'domReady!'
        ], function ($) {
            var linkStore = $('a[data-sm-store]');
            var dataLink;
            var dataPath = "";

            $(linkStore).each(function () {
                dataLink = $(this).attr('data-sm-link');

                if (typeof dataLink !== "undefined") {
                    dataPath = dataLink;
                }

                $(this).attr('href', "<?php echo $baseURL;?>" + $(this).attr('data-sm-store') + "/" + dataPath);
            });
        });
    </script>
<?php } ?>