;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; cPanel FPM Configuration ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; NOTICE This file is generated. Please use our WHM User Interface
; to set these values.

[technostationery_com]
catch_workers_output = yes
chdir = /home/technadminy7
group = "technadminy7"
listen = /opt/cpanel/ea-php82/root/usr/var/run/php-fpm/843b1a0571aeef5ee1517a7d713bc5ce591e43b5.sock
listen.group = "nobody"
listen.mode = 0660
listen.owner = "technadminy7"
php_admin_flag[allow_url_fopen] = on
php_admin_flag[log_errors] = on
php_admin_value[disable_functions] = passthru,shell_exec,system
php_admin_value[short_open_tag] = on
php_value[doc_root] = ""
php_value[error_log] = /home/technadminy7/logs/technostationery_com.php.error.log
php_value[error_reporting] = E_ALL & ~E_NOTICE
ping.path = /ping
pm = dynamic
pm.max_children = 12
pm.max_requests = 500
pm.max_spare_servers = 6
pm.min_spare_servers = 3
pm.process_idle_timeout = 10
pm.start_servers = 4
pm.status_path = /status
request_slowlog_timeout = 10s
slowlog = /home/technadminy7/logs/php-fpm-slow.log
security.limit_extensions = .phtml .php .php3 .php4 .php5 .php6 .php7 .php8
user = "technadminy7"
php_admin_value[memory_limit] = 2G
php_admin_value[max_execution_time] = 1800
php_admin_value[max_input_vars] = 10000
php_admin_value[realpath_cache_size] = 4096K
php_admin_value[realpath_cache_ttl] = 600