# PIM SSL VHost DocumentRoot - Akeneo PIM
DocumentRoot /home/pim/public_html/public

<Directory /home/pim/public_html/public>
    Options -Indexes +FollowSymLinks -MultiViews
    AllowOverride All
    Require all granted
    DirectoryIndex index.php
    DirectorySlash Off
    FallbackResource /index.php
</Directory>
